### ISSUE TITLE
Improve ListComponent item visibility

### ISSUE THREAD

**Issue by victorslkim** [Yelp/bento#2]
When a `ListComponent` has dividers, Bento will send an `onItemVisible()` and `onItemNotVisible()` for the dividers as well as the list items. 

This causes confusion to consumers of the `ListComponent` that expect to be able to use the provided index as the index of the items. 

We should have an alternative set of methods for `ListComponent` that only pertain to the items and not the dividers.

**Comment by redwarp** [comment]
Can't we remove the divider from the ListComponent? I always felt it had nothing to do there. It's opinionated about how to do UI, instead of providing building blocks.
