### ISSUE TITLE
there is some bug in ListComponent.onItemRangeInserted

### ISSUE THREAD

**Issue by eenie** [Yelp/bento#30]
when I append 3 datas in ListComponent 
it just can show one new item 
and then I append 3 datas again
it show the last 2 item , the new data is gone
and repeat
btw, I try it in the demo

**Comment by eenie** [comment]
the code is `  override fun onRefresh() {
        (componentController[1] as ListComponent<Nothing, String>).appendData((1..3).map { "List new element $it" })
        lay_swiper.isRefreshing = false
    }`

**Comment by dwaxemberg** [comment]
Thanks for reporting this! 

The issue is `ListComponent.appendData()` isn't respecting the dividers when it notifies that items have been inserted. If you disable the dividers in the list using `toggleDivider(false)`, your example will work properly.

**Comment by dwaxemberg** [comment]
Fixed by #33 

Bumping to `15.3.1` should solve your issue.
