### ISSUE TITLE
Making recyclerview not scrollable is hard

### ISSUE THREAD

**Issue by filipemp** [Yelp/bento#36]
Right now is not possible to have access to `LayoutManager` and make changes to its scrollable methods. We could expose scrolling options on the constructor or allow `RecyclerViewComponentController` to receive a `LayoutManager` making it more flexible to other use case.

I didn't went through all the controllers but I think either exposing `LayoutManager` properties or itself entirely are good options to increase flexibility for the recyclerview and decouple `RecyclerViewComponentController` from `LayoutManager`

**Comment by redwarp** [comment]
@filipemp Alternatively, we could assume that preventing scrolling is a needed feature sometimes, and simply support it?
Like, the Controller could have a "setScrollingEnabled(isEnabled: Boolean)" (and it would then control the LayoutManager, but internally)

**Comment by redwarp** [comment]
@filipemp the LayoutManager in Bento is already forced to be a GridLayoutManager, because that's how we support grid. That is why we don't allow free form LayoutManagers.
So we could also subclass the GridLayoutManager, like suggested here: https://stackoverflow.com/questions/30531091/how-to-disable-recyclerview-scrolling

**Comment by filipemp** [comment]
@redwarp tbh, I'm not sure which path would be better. Do we have a philosophy of Bento? sort of like, `Bento aims to make everyday decisions easier by making some of them for you`, or `Bento aims to have composable and flexible Grid, List, etc`. That might be helpful to make a decision on which approach to take.

**Comment by redwarp** [comment]
@filipemp bento aims at making the user forget there is such a thing as a recycler view. It abstract it notion.
You get your box, you compose it, and it is displayed. It can work with a recycler view, but also with a view pager, a list view....

**Comment by filipemp** [comment]
@redwarp it seems like adding `setScrollingEnabled(isEnabed: Boolean)` is the way to go then
